language: cpp

matrix:
  include:
  - os: linux
    compiler: clang
    env:
    - NODE_EXE: "iojs"
    - NODE_VERSION: "1.2.0"
  - os: linux
    compiler: clang
    env:
    - NODE_EXE: "node"
    - NODE_VERSION: "0.12.0"
  - os: linux
    compiler: clang
    env:
    - NODE_EXE: "node"
    - NODE_VERSION: "0.10.36"
  - os: linux
    compiler: gcc
    env:
    - NODE_EXE: "iojs"
    - NODE_VERSION: "1.2.0"
    - JOBS=8
  - os: linux
    compiler: gcc
    env:
    - NODE_EXE: "node"
    - NODE_VERSION: "0.12.0"
    - JOBS=8
  - os: linux
    compiler: gcc
    env:
    - NODE_EXE: "node"
    - NODE_VERSION: "0.10.36"
    - JOBS=8
  - os: osx
    compiler: clang
    env:
    - NODE_EXE: "iojs"
    - NODE_VERSION: "1.2.0"
  - os: osx
    compiler: clang
    env:
    - NODE_EXE: "node"
    - NODE_VERSION: "0.12.0"
  - os: osx
    compiler: clang
    env:
    - NODE_EXE: "node"
    - NODE_VERSION: "0.10.35"

env:
  global:
  - LD_LIBRARY_PATH: "/usr/local/lib"
  - secure: pz/HAMQpnde//JJi3f+RcW32APN6g3QyFAH41JlZwgsM5Daj9RRoXqUcNg4hEyTvlThtc5t+wQQ2ejYAjMwDu00GAzRFJ03Sm45w2fPvith9fu4crXsyPUvWUfWPC0ajTXzorN4cwFwOoMoeo9DihLwb0EC0n4T6jWdBCae3k+s=
  - secure: jYFAOQoMZkZVyc5AFPBKhR9oDqp5CciwCxFhVEHVjdImM+8V60loKazyw+bVLIjzKLnQbKKdiDudWL9TE1ylK/XSlF3K7o4gU2vIh5WzosKnU70Sanxd6tHt/Ui5eK+bAymKHbLdGiXIZtBZE0tML6+wgJ9vhV4ZKna5dM9tps4=

before_install:
- cd ./vendor/mbgl && source ./scripts/local_mason.sh && cd ../../
- source ./scripts/install_node.sh
- source ./vendor/mbgl/scripts/travis_helper.sh
- source ./vendor/mbgl/scripts/flags.sh
- source ./vendor/mbgl/scripts/travis_before_install.sh
- source ./scripts/setup_mesa.sh

install:
- npm install --build-from-source

before_script:
- ulimit -c unlimited -S

script:
- "./scripts/travis_test.sh"

after_success:
- "./scripts/travis_publish.sh"

git:
  submodules: true
